INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (1, '10회 편집 달성', '축하합니다! 10회 편집 횟수를 달성했습니다!', 'Achieve_Edit', 10, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (2, '100회 편집 달성', '축하합니다! 100회 편집 횟수를 달성했습니다!', 'Achieve_Edit', 100, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (3, '1000회 편집 달성', '축하합니다! 1000회 편집 횟수를 달성했습니다!', 'Achieve_Edit', 1000, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (4, '10000회 편집 달성', '어떻게 여기까지 온 거죠? 10000회 편집 횟수를 달성했습니다!', 'Achieve_Edit', 10000, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (5, '42회 편집 달성', '모든 것의 답안이 되는 42회 편집 횟수를 달성했습니다!', 'Achieve_Edit', 42, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (6, '300회 편집 달성', 'This is SPARTAAAAA!!! 300회 편집 횟수를 달성했습니다!', 'Achieve_Edit', 300, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (7, '500회 편집 달성', '어떻게 여기까지 온 거죠? 500회 편집 횟수를 달성했습니다!', 'Achieve_Edit', 500, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (8, '5000회 편집 달성', '어떻게 여기까지 온 거죠? 5000회 편집 횟수를 달성했습니다!', 'Achieve_Edit', 5000, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (9, '로컬 DB 게임에서 저장하기', '당신의 게임 진행도가 저장되는 게임에서 첫 저장을 하셨습니다! 당신의 즐거움은 헛되지 않아요.', 'System', 1, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (10, '파일 업로드', '리버티게임에 소중한 파일 자료를 올려주셨습니다! 감사합니다.', 'Achieve_Upload', 1, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (11, '게임 평가 완료!', '여러분의 소중한 게임 평가에 감사드립니다.', 'Achieve_Rate', 1, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (12, '적극적인 게임 평가자', '벌써 10번 평가해주셨군요! 감사합니다!', 'Achieve_Rate', 10, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (13, '게임 큐레이터', '벌써 게임에 50번 평가를 하셨네요! 이제 큐레이터라고 불러도 되겠습니다.', 'Achieve_Rate', 50, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (14, '평가에 치트를 썼나?', '게임들에 백만 번의 평가라고요? 리버티게임의 게임 수를 보았을 때 별점 평가 버튼을 마구잡이로 누른 것이 분명합니다! 부끄러운 기록일 수도 있습니다.', 'Achieve_Rate', 1000000, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (15, '특집 게임 메이커', '당신의 게임이 처음으로 특집 게임에 선정되었습니다!', 'System', 1, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (16, '토론자', '토론에 참여해주셔서 감사합니다.', 'Achieve_Talk', 1, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (17, '토론 매니아', '열성적인 토론가이시군요!', 'Achieve_Talk', 30, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (18, '최고의 수다쟁이', '토론 이름공간에서 이렇게 많은 이야기를 하다니, 대단합니다!', 'Achieve_Talk', 100, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (19, '첫 의사결정', '리버티게임의 운영에 중요한 의사 결정을 하셨습니다!', 'System', 1, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (20, '정책 결정자', '리버티게임의 운영에 큰 관심이 있으시군요! 혹시 관리자도 하실 생각이 없으십니까?', 'System', 50, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (21, '관리자로 당선!', '관리자 당선을 축하드립니다!', 'System', 1, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (22, '루아 프로그래밍의 시작', 'Lua로 만든 첫 프로그램 작성을 축하드립니다!', 'System', 1, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (23, '나의 첫 게임 배포!', '용감한 첫 도전에 감동했습니다! 이 양식대로 앞으로도 게임 배포 부탁드립니다.', 'System', 1, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (24, '첫 번째 광고', '당신이 만든 게임에 이제 여러 사람들이 찾아올 겁니다!', 'System', 1, NULL);
INSERT INTO achievement (idx, atitle, adescription, created_by, max_progress, game_name) VALUES (25, '애셋 크리에이터', '리버티게임에 소중한 파일 자료를 많이 올려주셨습니다. 정말 감사합니다!', 'Achieve_Upload', 10, NULL);