name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout from the repo
      uses: actions/checkout@v5
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Change gradle wrapper script to executable
      run: sudo chmod 755 ./gradlew
    - name: Build with Gradle
      run: sudo -S ./gradlew bootjar
    - name: Set QEMU system
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
      with:
        images: senouis/libertygame-achievement
        flavor: latest=true
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      with:
        username: senouis
        password: $DOCKER_PASSWORD
    - name: Build the Docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
