name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout from the repo
      uses: actions/checkout@v5
    - name: Set QEMU system
      uses: docker/setup-qemu-action@v3
    - name: Setup Java JDK and build Jar file
      uses: teheidoma/spring-boot-image-build-action@0.0.3
      with:
        jdk_dist: 17 # optional
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
      with:
        images: senouis/libertygame-achievement
        flavor: latest=true
    - name: Build the Docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: .
        platforms: linux/arm64
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
